# NumPy Opdrachten

In dit notebook vind je de volgende opdrachten:


- <a href="#np_opdracht1"> Opdracht 1</a> Maak deze opdracht ter voorbereiding op het college over NumPy.
- <a href="#np_opdracht2"> Opdracht 2</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht3"> Opdracht 3</a> Hiermee gaan we in het college aan de slag.
- <a href="#np_opdracht4"> Opdracht 4</a> Deze opdracht is facultatief, voor als je meer uitdaging wilt.

<a id="np_opdracht1"></a>
## Opdracht 1 
**Maak deze opdracht ter voorbereiding op het college**

In [57]:
import numpy as np

- Maak een 1D array x aan met de cijfers 0 t/m 5

In [58]:
x = np.ndarray([x for x in range(0,6)])
x

array([], shape=(0, 1, 2, 3, 4, 5), dtype=float64)

- Laat de vorm (grootte van de dimensies) van de array zien

In [59]:
x.shape

(0, 1, 2, 3, 4, 5)

- Hervorm de array x tot een 2D array (2, 3) 

In [60]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

- Wat is nu de vorm?


In [61]:
x.shape

(2, 3)

- Laat het datatype zien


In [62]:
x.dtype

dtype('int32')

- Sla een kopie van de array op in y


In [63]:
y = np.copy(arr)
y

array([[1, 2, 3],
       [4, 5, 6]])

- Maak een transpose van x



In [64]:
x = np.transpose(x)
x

array([[1, 4],
       [2, 5],
       [3, 6]])

- Maak een transpose van y


In [66]:
y = np.transpose(y)
y

array([[1, 4],
       [2, 5],
       [3, 6]])

- Vermenigvuldig alle waarden van y met 2


In [67]:
y *= 2
y

array([[ 2,  8],
       [ 4, 10],
       [ 6, 12]])

- Concateneer de twee arrays in een nieuwe array `z`


In [68]:
z = np.concatenate((x, y))
z

array([[ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [ 2,  8],
       [ 4, 10],
       [ 6, 12]])

- Geef het gemiddelde, modus, mediaan en de standaarddeviatie van z


In [78]:
from scipy import stats

average = np.mean(z)
mode = stats.mode(z)
median = np.median(z)
std = np.std(z)
           
freq,
average,
mode,
median,
std

3.2177890960513036

<a id="np_opdracht2"></a>
## Opdracht 2
**Python list vs. NumPy**

- Maak een list `lst` met 1.000.001 willekeurige getallen tussen 0 en 10 (gebruik `random.randint(0, 10)`)
- Bepaal de mediaan
- Maak een list met daarin het kwadraat van elk element in `lst`
- Maak een list met daarin alleen alle even getallen uit `lst`
- Maak een tweede list `lst2` met 1.000.001 willekeurige getallen
- Maak een list met daarin de som van de elementen uit `lst` en `lst2`, dus:
  - `lst_samen[0] = lst[0] + lst2[0]`,
  - `lst_samen[1] = lst[1] + lst2[1]`,
  - etc.

- Doe bovenstaande ook met Numpy

- Gebruik `%timeit` voor je code om de snelheid te vergelijken

In [9]:
import math
import random
import numpy as np

In [21]:
lst = np.array([random.randint(0,10) for _ in range(0, 10**6 + 1)])

median = np.median(lst)
median

lst_kwdrt = np.array([x**2 for x in lst])
lst_even = np.array([x for x in lst if x % 2 == 0])

lst2 = np.array([random.randint(0,10) for _ in range(0, 10**6 + 1)])

lst_samen = np.add(lst, lst2)
print(lst[0])
print(lst2[0])
print(lst_samen[0])


9
6
15


<a id="np_opdracht3"></a>
## Opdracht 3

De blokcoördinator D.O. Cent van blok A  wil graag de cijfers analyseren en verwerken. Het blok bestaat uit 3 vakken, die door 10 studenten gevolgd zijn. Analyse omvat o.a. het bepalen van gemiddelde cijfer, het aantal voldoendes en cursusrendement. De verwerking bestaat uit het corrigeren van de cijfers.

In `blokAcijfers.txt` staan de cijfers per vak (naast elkaar staan de vakken, onder elkaar de studenten):

vak1 | vak2 | vak3
----|-------|------
6.5 | 7.3   | 6.4
8.0 | 8.0	| 8.5
3.2	| 4.0	| 5.0
7.9	| 7.1	| 3.5
7.3	| 7.8	| 8.0
8.6	| 8.0	| 9.0
4.0	| 6.0	| 5.5
7.3	| 7.8	| 7.8
4.5	| 5.6	| 7.7
5.0	| 7.0	| 7.2


In [23]:
import numpy as np

Start met de data verzamelen:
- Lees tekstbestand: blokAcijfers.txt in met `np.loadtxt`, sla de data op in een numpy array met naam `vCijfers`.
- Laat zien dat de gegevens goed ingelezen zijn.
- Toon de array attributen.

In [36]:
text = np.loadtxt("blokAcijfers.txt")
text

array([[6.5, 7.3, 6.4],
       [8. , 8. , 8.5],
       [3.2, 4. , 5. ],
       [7.9, 7.1, 3.5],
       [7.3, 7.8, 8. ],
       [8.6, 8. , 9. ],
       [4. , 6. , 5.5],
       [7.3, 7.8, 7.8],
       [4.5, 5.6, 7.7],
       [5. , 7. , 7.2]])

De docent ziet dat er 2 cijfers fout zijn en wil deze corrigeren
-	Wijzig de volgende cijfers:
    *	vak-2, student-3  cijfer 4.0 moet 4.3 worden.
    *	vak-1, student-10, cijfer 5.0 moet 4.8 worden.

In [37]:
text[2][1] = 4.3
text[9][0] = 4.8

text 

array([[6.5, 7.3, 6.4],
       [8. , 8. , 8.5],
       [3.2, 4.3, 5. ],
       [7.9, 7.1, 3.5],
       [7.3, 7.8, 8. ],
       [8.6, 8. , 9. ],
       [4. , 6. , 5.5],
       [7.3, 7.8, 7.8],
       [4.5, 5.6, 7.7],
       [4.8, 7. , 7.2]])

De docent wil wat basisgegevens weten.
-	Bepaal minimum, maximum en gemiddelde van alle cijfers.
-	Bepaal minimum, maximum en gemiddelde van elk vak (3 getallen).
-	Bepaal minimum, maximum en gemiddelde van elke student (10 getallen).

In [50]:
# For all grades:
min = np.min(text)
max = np.max(text)
median = np.median(text)

# For every class
for i in range(len(text[0])):
    column = text[:,i]
    print(f"for class {i+1}")
    print(f"min    = {np.min(column)}")
    print(f"max    = {np.max(column)}")
    print(f"median = {round(np.median(column),2)}")
        

for class 1
min    = 3.2
max    = 8.6
median = 6.9
for class 2
min    = 4.3
max    = 8.0
median = 7.2
for class 3
min    = 3.5
max    = 9.0
median = 7.45


De docent wil graag zien wat de cijfers zijn als ze afgerond worden op hele getallen.
-	Kopieer de array naar een nieuwe array.
-	Rond de waarden af.
-	Laat de resultaten zien.

In [79]:
lst2 = np.copy(text).round()
lst2

array([[6., 7., 6.],
       [8., 8., 8.],
       [3., 4., 5.],
       [8., 7., 4.],
       [7., 8., 8.],
       [9., 8., 9.],
       [4., 6., 6.],
       [7., 8., 8.],
       [4., 6., 8.],
       [5., 7., 7.]])

Er is een fout gemaakt bij de cijfers van het 1e vak. Iedere student krijgt 0.5 punt extra erbij.
-	Vul een ‘ophoogarray’ bestaande uit 3 kolommen en elk 10 rijen en vul deze eerst met 0.0 en daarna de eerste rij met de waarden 0.5.
-	Tel de ophoogarray op bij de cijfer array.

In [84]:
lst3 = np.zeros((10,3))
lst3[:,0] += 0.5

lst4 = np.add(text, lst3)
lst4

array([[7. , 7.3, 6.4],
       [8.5, 8. , 8.5],
       [3.7, 4.3, 5. ],
       [8.4, 7.1, 3.5],
       [7.8, 7.8, 8. ],
       [9.1, 8. , 9. ],
       [4.5, 6. , 5.5],
       [7.8, 7.8, 7.8],
       [5. , 5.6, 7.7],
       [5.3, 7. , 7.2]])

De docent wil een lijstje waarin hij in één opslag ziet waar een voldoende (`True`) en waar een onvoldoende (`False`) staat.  
-	Maakt dit lijstje.

In [88]:
lst5 = np.zeros((10,3), dtype="bool")



array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

<a id="np_opdracht4"></a>
## Opdracht 4
**Deze opdracht is facultatief**

In [ ]:
import numpy as np

#### 3. Create a null vector of size 10

#### 6.  Create a null vector of size 10 but the fifth value which is 1

#### 8.  Reverse a vector with values ranging from 10 to 49 (first element becomes last)

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

#### 11. Create a 3x3 identity matrix

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

#### 15. Create a 2d array with 1 on the border and 0 inside

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

#### 29. How to round away from zero a float array ?

#### 30. How to find common values between two arrays?

#### 36. Extract the integer part of a random array using 5 different methods

In [ ]:
Z = np.random.uniform(0,10,10)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

#### 40. Create a random vector of size 10 and sort it

#### 42. Consider two random array A and B, check if they are equal

#### 45. Create random vector of size 10 and replace the maximum value by 0

#### 50. How to find the closest value (to a given scalar) in a vector?

In [ ]:
v = np.random.uniform(0,100)

#### 52. Consider a random vector with shape (10,2) representing coordinates, find point by point distances

In [ ]:
Z = np.random.random((10,2))


#### 57. How to randomly place p elements in a 2D array?

#### 58. Subtract the mean of each row of a matrix

#### 59. How to sort an array by the nth column?

#### 60. How to tell if a given 2D array has null columns?

#### 61. Find the nearest value from a given value in an array

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value?

#### 72. How to swap two rows of an array?

#### 77. How to negate a boolean, or to change the sign of a float inplace?

#### 83. How to find the most frequent value in an array?

#### 89. How to get the n largest values of an array